services:
  api:
    image: absolutekino-dev:latest  
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
