services:
  api:
    image: absolutekino:latest  
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - "3000:3000"
    env_file:
      - .env     
    environment:
      - NODE_ENV=prod
    volumes:
      - ./db.sqlite:/app/db.sqlite
    restart: always          