services:
  api:
    image: absolutekino-dev:latest  
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${EXTERNAL_PORT:-3002}:${APP_PORT:-3000}"
    env_file:
      - .env
    command: npm run dev
