POST http://localhost:3000/cinema/new HTTP/1.1
content-type: application/json

{
    "name": "absolute",
    "address": "ul. Uwunia 12a/34, 31-888 Uwu, Warszawa, Polska",
    "latitude": 25.4,
    "longitude": 45.6
}